### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by dikeckaan** [hsmnzaydn/AfterFromManjaro#1]
when i want to install some packages its  stop here why?  [http://imgur.com/a/kDi7f](http://imgur.com/a/kDi7f)
Turkce anlatmak gerekirse : kurmak istediğim paketleri seçiyorum ve burda kalıyor yaklaşık 30 dk dan beri aynı hala yardımlarınızı bekliyorum

**Comment by hsmnzaydn** [comment]
i couldn't see img.Can you upload to another website?

**Comment by dikeckaan** [comment]
http://indirmelik.kaandikec.com/AfterFromManjaro.png its my server

**Comment by Anticolick** [comment]
`sudo python AfterManjaro.py
[sudo] password for kaandikec: 
error: target not found: wget
error: target not found: base-devel
error: target not found: yaourt
.: Info Downloading mirrors from repo.manjaro.org
.: Info Using default mirror file
.: Info Querying mirrors - This may take some time
   0.852 Australia      : http://mirror.ventraip.net.au/Manjaro/
   1.490 Australia      : http://manjaro.uberglobalmirror.com/
   ..... Australia      : http://manjaro.mirror.serversaustralia.com.au/
   0.851 Austria        : http://mirror.inode.at/manjaro/
   0.365 Belarus        : http://mirror.datacenter.by/pub/mirrors/manjaro/
   ..... Belgium        : http://ftp.belnet.be/manjaro/
   1.738 Belgium        : ftp://ftp.belnet.be/mirrors/manjaro/
   0.840 Belgium        : https://manjaro.cu.be/
   1.100 Brasil         : http://linorg.usp.br/manjaro/
   1.078 Bulgaria       : https://mirrors.netix.net/manjaro/
   0.807 Bulgaria       : https://manjaro.ipacct.com/manjaro/
   0.588 Bulgaria       : http://manjaro.telecoms.bg/
   0.824 Canada         : https://ca.mirror.babylon.network/manjaro/
   1.889 Chile          : http://manjaro.dcc.uchile.cl/
   ..... Chile          : http://doge.ing.puc.cl/Mirrors/Manjaro/
   ..... China          : https://mirrors.ustc.edu.cn/manjaro/
   1.222 China          : http://ftp.cuhk.edu.hk/pub/Linux/manjaro/
   ..... China          : http://mirrors.tuna.tsinghua.edu.cn/manjaro/
   2.758 China          : https://mirrors.zju.edu.cn/manjaro/
   ..... Colombia       : http://mirror.edatel.net.co/manjaro/
   ..... Costa_Rica     : https://mirrors.ucr.ac.cr/manjaro/
.: Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) 'https://mirrors.ucr.ac.cr/manjaro/'

   1.302 Czech          : https://mirror.dkm.cz/manjaro/
   0.585 Denmark        : https://mirrors.dotsrc.org/manjaro/
   0.861 Denmark        : https://www.uex.dk/repos/manjaro/
   2.230 Ecuador        : https://mirror.cedia.org.ec/manjaro/
   1.987 Ecuador        : https://mirror.uta.edu.ec/manjaro/
   1.375 Ecuador        : https://mirror.espoch.edu.ec/manjaro/
   0.438 France         : http://manjarolinux.polymorf.fr/
   0.684 France         : http://mirror.lignux.com/manjaro/
   0.611 France         : http://ftp.free.org/mirrors/repo.manjaro.org/repos/
   0.610 France         : https://fr.mirror.babylon.network/manjaro/
   0.458 Germany        : http://mirror.ragenetwork.de/manjaro/
   2.761 Germany        : https://ftp.halifax.rwth-aachen.de/manjaro/
   0.263 Germany        : http://ftp.tu-chemnitz.de/pub/linux/manjaro/
   0.673 Germany        : https://mirror.netzspielplatz.de/manjaro/packages/
   0.597 Germany        : https://mirror.netcologne.de/manjaro/
   0.525 Germany        : https://repo.rhindon.net/manjaro/
   0.724 Germany        : https://repo.stdout.net/manjaro/
   0.490 Germany        : https://mirror.alpix.eu/manjaro/
   0.634 Germany        : https://manjaro-mirror-a.alpix.eu/
   0.469 Germany        : http://ftp.rz.tu-bs.de/pub/mirror/manjaro.org/repos/
   0.695 Germany        : https://manjaro.ieji.de/
   0.628 Hungary        : http://mirror.infotronik.hu/mirrors/pub/manjaro/
   ..... Indonesia      : http://kambing.ui.ac.id/manjaro/
   0.614 Indonesia      : http://kartolo.sby.datautama.net.id/manjaro/
   0.659 Ireland        : https://ftp.heanet.ie/mirrors/manjaro/
   0.970 Italy          : https://manjaro.mirror.garr.it/mirrors/manjaro/
   0.584 Italy          : https://ba.mirror.garr.it/mirrors/manjaro/
   0.906 Italy          : https://ct.mirror.garr.it/mirrors/manjaro/
   ..... Japan          : http://ftp.tsukuba.wide.ad.jp/Linux/manjaro/
   1.167 Japan          : http://ftp.riken.jp/Linux/manjaro/
   0.503 Netherlands    : https://ftp.nluug.nl/pub/os/Linux/distr/manjaro/
   0.275 Netherlands    : http://ftp.snt.utwente.nl/pub/linux/manjaro/
   0.628 Netherlands    : https://nl.mirror.babylon.network/manjaro/
   ..... Netherlands    : https://manjaro.mirror.wearetriple.com/
   1.896 Philippines    : http://mirror.rise.ph/manjaro/
   ..... Poland         : http://mirror.chmuri.net/manjaro/
.: Error [Errno 113] No route to host 'http://mirror.chmuri.net/manjaro/'

   0.669 Portugal       : http://ftp.dei.uc.pt/pub/linux/manjaro/
   ..... Portugal       : http://manjaro.barata.pt/
.: Error [Errno 111] Connection refused 'http://manjaro.barata.pt/'

   0.529 Romania        : http://mirrors.serverhost.ro/manjaro/packages/
   1.077 Romania        : http://ftp.lug.ro/manjaro/
   0.604 Russia         : https://mirror.yandex.ru/mirrors/manjaro/
   3.661 Singapore      : https://download.nus.edu.sg/mirror/manjaro/
   ..... South_Africa   : http://mirror.is.co.za/mirrors/manjaro.org/
   1.194 Sweden         : https://ftp.lysator.liu.se/pub/manjaro/
   0.837 Spain          : http://ftp.caliu.cat/manjaro/
   0.807 Sweden         : https://mirror.zetup.net/manjaro/
   1.497 Taiwan         : http://free.nchc.org.tw/manjaro/
   0.154 Turkey         : http://ftp.linux.org.tr/manjaro/
   0.613 United_Kingdom : http://repo.manjaro.org.uk/
   1.179 United_Kingdom : https://www.mirrorservice.org/sites/repo.manjaro.org/r
   0.685 United_Kingdom : http://mirror.catn.com/pub/manjaro/
   0.556 United_Kingdom : http://manjaro.mirrors.uk2.net/
   0.568 United_States  : http://mirror.dacentec.com/manjaro/
   0.911 United_States  : http://mirror.jmu.edu/manjaro/
   0.574 United_States  : http://mirror.solarvps.com/manjaro/
   ..... United_States  : http://mirror.nexcess.net/manjaro/
   0.825 United_States  : http://distro.ibiblio.org/manjaro/
   1.254 United_States  : https://mirror.clarkson.edu/manjaro/
   2.333 United_States  : https://mirrors.ocf.berkeley.edu/manjaro/
   1.807 Vietnam        : https://mirror.freedif.org/Manjaro/
.: Info Writing mirror list
   Turkey          : http://ftp.linux.org.tr/manjaro/stable
   Germany         : http://ftp.tu-chemnitz.de/pub/linux/manjaro/stable
   Netherlands     : http://ftp.snt.utwente.nl/pub/linux/manjaro/stable
   Belarus         : http://mirror.datacenter.by/pub/mirrors/manjaro/stable
   France          : http://manjarolinux.polymorf.fr/stable
   Germany         : http://mirror.ragenetwork.de/manjaro/stable
   Germany         : http://ftp.rz.tu-bs.de/pub/mirror/manjaro.org/repos/stable
   Germany         : https://mirror.alpix.eu/manjaro/stable
   Netherlands     : https://ftp.nluug.nl/pub/os/Linux/distr/manjaro/stable
   Germany         : https://repo.rhindon.net/manjaro/stable
   Romania         : http://mirrors.serverhost.ro/manjaro/packages/stable
   United_Kingdom  : http://manjaro.mirrors.uk2.net/stable
   United_States   : http://mirror.dacentec.com/manjaro/stable
   United_States   : http://mirror.solarvps.com/manjaro/stable
   Italy           : https://ba.mirror.garr.it/mirrors/manjaro/stable
   Denmark         : https://mirrors.dotsrc.org/manjaro/stable
   Bulgaria        : http://manjaro.telecoms.bg/stable
   Germany         : https://mirror.netcologne.de/manjaro/stable
   Russia          : https://mirror.yandex.ru/mirrors/manjaro/stable
   France          : https://fr.mirror.babylon.network/manjaro/stable
   France          : http://ftp.free.org/mirrors/repo.manjaro.org/repos/stable
   United_Kingdom  : http://repo.manjaro.org.uk/stable
   Indonesia       : http://kartolo.sby.datautama.net.id/manjaro/stable
   Hungary         : http://mirror.infotronik.hu/mirrors/pub/manjaro/stable
   Netherlands     : https://nl.mirror.babylon.network/manjaro/stable
   Germany         : https://manjaro-mirror-a.alpix.eu/stable
   Ireland         : https://ftp.heanet.ie/mirrors/manjaro/stable
   Portugal        : http://ftp.dei.uc.pt/pub/linux/manjaro/stable
   Germany         : https://mirror.netzspielplatz.de/manjaro/packages/stable
   France          : http://mirror.lignux.com/manjaro/stable
   United_Kingdom  : http://mirror.catn.com/pub/manjaro/stable
   Germany         : https://manjaro.ieji.de/stable
   Germany         : https://repo.stdout.net/manjaro/stable
   Bulgaria        : https://manjaro.ipacct.com/manjaro/stable
   Sweden          : https://mirror.zetup.net/manjaro/stable
   Canada          : https://ca.mirror.babylon.network/manjaro/stable
   United_States   : http://distro.ibiblio.org/manjaro/stable
   Spain           : http://ftp.caliu.cat/manjaro/stable
   Belgium         : https://manjaro.cu.be/stable
   Austria         : http://mirror.inode.at/manjaro/stable
   Australia       : http://mirror.ventraip.net.au/Manjaro/stable
   Denmark         : https://www.uex.dk/repos/manjaro/stable
   Italy           : https://ct.mirror.garr.it/mirrors/manjaro/stable
   United_States   : http://mirror.jmu.edu/manjaro/stable
   Italy           : https://manjaro.mirror.garr.it/mirrors/manjaro/stable
   Romania         : http://ftp.lug.ro/manjaro/stable
   Bulgaria        : https://mirrors.netix.net/manjaro/stable
   Brasil          : http://linorg.usp.br/manjaro/stable
   Japan           : http://ftp.riken.jp/Linux/manjaro/stable
   United_Kingdom  : https://www.mirrorservice.org/sites/repo.manjaro.org/repos/
   Sweden          : https://ftp.lysator.liu.se/pub/manjaro/stable
   China           : http://ftp.cuhk.edu.hk/pub/Linux/manjaro/stable
   United_States   : https://mirror.clarkson.edu/manjaro/stable
   Czech           : https://mirror.dkm.cz/manjaro/stable
   Ecuador         : https://mirror.espoch.edu.ec/manjaro/stable
   Australia       : http://manjaro.uberglobalmirror.com/stable
   Taiwan          : http://free.nchc.org.tw/manjaro/stable
   Belgium         : ftp://ftp.belnet.be/mirrors/manjaro/stable
   Vietnam         : https://mirror.freedif.org/Manjaro/stable
   Chile           : http://manjaro.dcc.uchile.cl/stable
   Philippines     : http://mirror.rise.ph/manjaro/stable
   Ecuador         : https://mirror.uta.edu.ec/manjaro/stable
   Colombia        : http://mirror.edatel.net.co/manjaro/stable
   Ecuador         : https://mirror.cedia.org.ec/manjaro/stable
   United_States   : https://mirrors.ocf.berkeley.edu/manjaro/stable
   Australia       : http://manjaro.mirror.serversaustralia.com.au/stable
   Japan           : http://ftp.tsukuba.wide.ad.jp/Linux/manjaro/stable
   South_Africa    : http://mirror.is.co.za/mirrors/manjaro.org/stable
   China           : https://mirrors.zju.edu.cn/manjaro/stable
   Germany         : https://ftp.halifax.rwth-aachen.de/manjaro/stable
   United_States   : http://mirror.nexcess.net/manjaro/stable
   Chile           : http://doge.ing.puc.cl/Mirrors/Manjaro/stable
   Indonesia       : http://kambing.ui.ac.id/manjaro/stable
   Singapore       : https://download.nus.edu.sg/mirror/manjaro/stable
   China           : http://mirrors.tuna.tsinghua.edu.cn/manjaro/stable
   China           : https://mirrors.ustc.edu.cn/manjaro/stable
   Belgium         : http://ftp.belnet.be/manjaro/stable
   Netherlands     : https://manjaro.mirror.wearetriple.com/stable
   Costa_Rica      : https://mirrors.ucr.ac.cr/manjaro/stable
   Poland          : http://mirror.chmuri.net/manjaro/stable
   Portugal        : http://manjaro.barata.pt/stable
.: Info Mirrorlist generated and saved to: /etc/pacman.d/mirrorlist
:: Synchronizing package databases...
 core                     139,9 KiB   154K/s 00:01 [######################] 100%
 extra                   1800,0 KiB   185K/s 00:10 [######################] 100%
 community                  4,2 MiB   197K/s 00:22 [######################] 100%
 multilib                 180,7 KiB   113K/s 00:02 [######################] 100%
^C

`

**Comment by hsmnzaydn** [comment]
Kardeş sen Türk müsün ya :) .Hangi programları yüklemeye çalışıyorsun.Eğer hiçbir program seçmeden direk "install" tuşuna bastıysan yapması gereken şeyi yapıyor zaten.Eğer bir program yüklemek istiyorsan paketlerden birini seçmen lazım.
